# Generated by Django 4.1.2 on 2022-10-28 15:24

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_post_like_count_post_subtitle_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=model_utils.fields.StatusField(choices=[('movies', 'movies'), ('shows', 'shows'), ('books', 'books')], default='movies', max_length=100, no_check_for_status=True),
        ),
    ]
