# Generated by Django 4.1.2 on 2022-11-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_year_of_release'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_url',
            field=models.TextField(default='fg'),
            preserve_default=False,
        ),
    ]
